FactoryBot.define do
  factory :url do
    original_url { "https://example.com/some/very/long/path/to/a/resource?with=parameters&and=more" }

    # shortened_path is generated by the model on create. Set it explicitly in a
    # spec when the value matters; the model no longer overwrites it.

    trait :anonymous do
      user { nil }
    end

    trait :owned do
      association :user
    end

    trait :with_visits do
      transient { visit_count { 3 } }

      after(:create) do |url, evaluator|
        create_list(:visit, evaluator.visit_count, url: url)
        Url.reset_counters(url.id, :visits)
        url.reload
      end
    end
  end
end
