module UrlsHelper
  # Generate the full short URL with the host. Named full_short_url because
  # `short_url` is already taken by the route helper generated by `as: :short`.
  def full_short_url(path)
    "#{request.base_url}/#{path}"
  end

  # Format large numbers with commas
  def format_number(number)
    number_with_delimiter(number)
  end

  # Create a QR code for the URL.
  # TODO(phase 4): generate these locally with rqrcode - this sends every
  # shortened link, and the viewer's IP, to a third party.
  def qr_code_url(url, size = 200)
    "https://api.qrserver.com/v1/create-qr-code/?size=#{size}x#{size}&data=#{CGI.escape(url)}"
  end

  # Share of a total, guarding against the empty case.
  def share_of(count, total)
    return number_to_percentage(0, precision: 1) if total.to_i.zero?

    number_to_percentage(count.to_f / total * 100, precision: 1)
  end
end
