module UrlsHelper
  # Generate the full short URL with the host. Named full_short_url because
  # `short_url` is already taken by the route helper generated by `as: :short`.
  def full_short_url(path)
    "#{request.base_url}/#{path}"
  end

  # Format large numbers with commas
  def format_number(number)
    number_with_delimiter(number)
  end

  # An inline SVG QR code for the given URL. Generated locally: this used to be
  # an <img> pointing at api.qrserver.com, which sent every shortened link and
  # the viewer's IP to a third party and broke without a network connection.
  def qr_code_svg(url, size: 200)
    svg = RQRCode::QRCode.new(url).as_svg(
      module_size: 4,
      standalone: true,
      use_path: true,
      viewbox: true,
      svg_attributes: {
        width: size,
        height: size,
        role: "img",
        class: "img-thumbnail bg-white",
        "aria-label": "QR code for #{url}"
      }
    )

    svg.html_safe # rubocop:disable Rails/OutputSafety -- generated by RQRCode, not user input
  end

  # Share of a total, guarding against the empty case.
  def share_of(count, total)
    return number_to_percentage(0, precision: 1) if total.to_i.zero?

    number_to_percentage(count.to_f / total * 100, precision: 1)
  end
end
